BOT_NAME = "carbonrag_policy_crawler"

SPIDER_MODULES = ["app.knowledge.policy_scrapy_spider"]
NEWSPIDER_MODULE = "app.knowledge.policy_scrapy_spider"

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 2.0
AUTOTHROTTLE_MAX_DELAY = 10.0
CLOSESPIDER_PAGECOUNT = 20
CLOSESPIDER_TIMEOUT = 60
CONCURRENT_REQUESTS_PER_DOMAIN = 1
COOKIES_ENABLED = False
DEPTH_LIMIT = 1
DNSCACHE_ENABLED = True
DOWNLOAD_DELAY = 2.0
DOWNLOAD_MAXSIZE = 25 * 1024 * 1024
DOWNLOAD_TIMEOUT = 60
DOWNLOAD_WARNSIZE = 10 * 1024 * 1024
FEED_EXPORT_ENCODING = "utf-8"
HTTPPROXY_ENABLED = True
REDIRECT_ENABLED = True
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
RETRY_ENABLED = True
RETRY_HTTP_CODES = [408, 429, 500, 502, 503, 504, 522, 524]
RETRY_TIMES = 2
ROBOTSTXT_OBEY = True
TELNETCONSOLE_ENABLED = False
USER_AGENT = "CarbonRagPolicyCrawler/1.0 (+admin-reviewed)"
